import os
import re
import shutil
import subprocess
from typing import Any, Dict, Tuple


def _resolve_kicad_cli() -> str:
    env_path = os.environ.get("KICAD_CLI", "").strip()
    if env_path and os.path.exists(env_path):
        return env_path

    which_path = shutil.which("kicad-cli")
    if which_path:
        return which_path

    mac_bundle_path = "/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli"
    if os.path.exists(mac_bundle_path):
        return mac_bundle_path

    return "kicad-cli"


def export_board_svg(board_file: str, output_dir: str) -> Dict[str, Any]:
    os.makedirs(output_dir, exist_ok=True)
    out_dir = os.path.join(output_dir, "snapshots")
    os.makedirs(out_dir, exist_ok=True)

    cli = _resolve_kicad_cli()
    cmd = [
        cli,
        "pcb",
        "export",
        "svg",
        "--output",
        out_dir,
        board_file,
    ]

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=False)
        if result.returncode != 0:
            return {
                "ok": False,
                "message": "Failed to export PCB SVG.",
                "stderr": result.stderr,
                "command": cmd,
            }

        svg_files = [name for name in os.listdir(out_dir) if name.lower().endswith(".svg")]
        svg_files.sort()
        if not svg_files:
            return {
                "ok": False,
                "message": "No SVG generated by kicad-cli.",
                "stderr": result.stderr,
                "command": cmd,
            }

        return {
            "ok": True,
            "svg_path": os.path.join(out_dir, svg_files[0]),
            "command": cmd,
        }
    except FileNotFoundError:
        return {
            "ok": False,
            "message": "kicad-cli not found",
            "command": cmd,
        }


def _parse_svg_size(svg_text: str) -> Tuple[float, float]:
    viewbox_match = re.search(r'viewBox="([^"]+)"', svg_text)
    if viewbox_match:
        parts = viewbox_match.group(1).replace(",", " ").split()
        if len(parts) == 4:
            try:
                return float(parts[2]), float(parts[3])
            except Exception:
                pass

    width_match = re.search(r'width="([0-9.]+)', svg_text)
    height_match = re.search(r'height="([0-9.]+)', svg_text)
    if width_match and height_match:
        try:
            return float(width_match.group(1)), float(height_match.group(1))
        except Exception:
            pass

    return 1000.0, 1000.0


def add_svg_marker(svg_path: str, x_percent: float, y_percent: float, label: str) -> Dict[str, Any]:
    if not os.path.exists(svg_path):
        return {"ok": False, "message": "SVG file not found."}

    with open(svg_path, "r", encoding="utf-8") as stream:
        svg = stream.read()

    width, height = _parse_svg_size(svg)
    x = max(0.0, min(100.0, x_percent)) / 100.0 * width
    y = max(0.0, min(100.0, y_percent)) / 100.0 * height

    marker = (
        f'<g id="ai-review-marker">'
        f'<circle cx="{x:.2f}" cy="{y:.2f}" r="18" fill="none" stroke="#ff2a2a" stroke-width="4" />'
        f'<line x1="{x - 26:.2f}" y1="{y:.2f}" x2="{x + 26:.2f}" y2="{y:.2f}" stroke="#ff2a2a" stroke-width="4" />'
        f'<line x1="{x:.2f}" y1="{y - 26:.2f}" x2="{x:.2f}" y2="{y + 26:.2f}" stroke="#ff2a2a" stroke-width="4" />'
        f'<text x="{x + 28:.2f}" y="{y - 22:.2f}" fill="#ff2a2a" font-size="20" font-family="Helvetica">{label}</text>'
        f'</g>'
    )

    if "</svg>" not in svg:
        return {"ok": False, "message": "Invalid SVG file."}

    annotated = svg.replace("</svg>", marker + "</svg>")
    output_path = svg_path[:-4] + "_annotated.svg"
    with open(output_path, "w", encoding="utf-8") as stream:
        stream.write(annotated)

    return {"ok": True, "annotated_svg": output_path}
